# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sendMessage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashValue', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='hashValue',
        ),
        migrations.AddField(
            model_name='userhash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendMessage.User'),
        ),
    ]
