# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendMessage', '0002_auto_20161222_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
