# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendMessage', '0003_auto_20161222_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdata',
        ),
    ]
